import { Inter } from 'next/font/google'
import '~styles/common/globals.css'
import '~styles/common/site.scss'
import cn from 'classnames'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Impossible Means Nothing',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'adidas-body')}>{children}</body>
    </html>
  )
}
